=== A: Description of ReaClassical Functions

_Preliminary Note:_ These proceed in a quasi-workflow order. I include the default shortcut keys if using my portable install or resource folder base. You can also use the custom toolbar via the mouse.

*Create/Sync Horizontal Workflow* kbd:[F7]

_Description:_ The way to create a horizontal workflow with a single folder group with as many tracks as you need. It can also be used with an single existing folder group to re-sync track names and re-build project routing.

_Notes:_ Use on a completely empty project. I would use this if you are planning to use a horizontal approach to source-destination editing (i.e. the various takes are laid out from left to right) or if you want a quick way to set up a mixing/mastering track set with a single take. The function automatically sets up the tracks for group media and razor-editing along with dedicated mixer tracks. These mixer tracks should be used for all track settings (names, volume, pan, polarity, sends and FX).

*Create/Sync Vertical Workflow* kbd:[F8]

_Description:_ A multi-use function to 1) set up a vertical workflow with destination and source groups with as many tracks as you need, 2) to create source groups from an existing destination folder group (for example, created with kbd:[F7] shortcut) and, for in the middle of editing, 3) to (re)create project routing and sync track-naming, record inputs and lock states. Note that for 3), all folders should contain the same number of tracks.

_Notes:_ For all track settings (names, volume, pan, polarity, sends and FX) you should use the dedicated mixer tracks.

*Explode multi-channel item* kbd:[F10]

_Description:_ Explode multi-channel item(s) to either all mono or stereo-interleaved + mono

_Notes:_ Import your multi-channel media using a single regular track (for a horizontal workflow) or multiple regular tracks (for a vertical workflow). Then, simply press (no need to select the items). Answer btn:[yes] to the prompt that appears if the first two channels should be treated as stereo interleaved (i.e. they represent your main pair). Depending on the choice made, the number of tracks in the resulting folder(s) will adjust accordingly. Then you are given the opportunity to name your tracks. Obviously if you decide to move to a vertical workflow after exploding using a single track, you can always use kbd:[F8] to create your source folders then drag the media to where you want them. If you need to bring in new takes after editing has started, simply use the function on an empty project tab then copy or cut them into the original project tab into the desired folder on the timeline.

*Add special track(s)* kbd:[#]

_Description:_ Adds one or more special tracks (aux, submix, roomtone, reference)

_Notes:_ ReaClassical projects can have any number of special tracks but are limited to a single roomtone track. See below for details of each kind of track.

Aux send: Add a rosewood-colored aux track prefixed with an ampersand (`@`) to the end of the track list but is only visible in the mixer. This allows the user to keep assigned aux tracks visible in the intelligent mixer. Create any connections to the aux in the destination group (including child tracks) and then push to the source groups via the Vertical Workflow function kbd:[F8]. This routing is maintained during subsequent or kbd:[F8] syncs. Set Maintain Mixer => RCMASTER to 0 to add a hyphen (-) to the end of every mixer track thereby removing the direct connection to RCMASTER allowing for all sorts of nice custom routing. By default the final option is always set to 1 to maintain whatever routing you currently have.

Submix: Add a teal-colored aux track prefixed with an hash (#) to the end of the track list but is only visible in the mixer. This allows the user to keep assigned submix tracks visible in the intelligent mixer. Create any connections to the submix in the destination group (including child tracks) and then push to the source groups via the Vertical Workflow function kbd:[F8]. For correct routing to a submix (versus a send), simply add a hyphen (-) at the end of desired track names in the mixer tracks and sync via kbd:[F7] or kbd:[F8]. Now those related mixer tracks will not route directly to RCMASTER. As an example, say tracks 3-6 are all string section microphones and you'd like to first sum them all to a string submix track called _#strings_. Just add a hyphen to the end of the names for tracks 3-6, sync and then create the routing to #strings via click-dragging from the routing stripes. This routing is maintained during subsequent kbd:[F7] or kbd:[F8] syncs.

Room tone: Add a burnt sienna-colored aux/submix track labeled _RoomTone_ to the end of the track list that is visible in both the track and mixer panels. The track will be included in the signal path via the regular audition function kbd:[A]. If present when creating CD/DDP via the function will also generate volume automation to create perfect crossfades with the items on the first destination track. Slicing and dicing room tone audio to fill in digital silence is now a thing of the past. Simply add a long recorded or convolution-generated room tone audio item before running the function. The ReaClassical way of dealing with room tone is non-destructive and instant!

Reference: Add a reference track labeled _REF_ to the end of the track list that is visible in both the track and mixer panels. If you rename, a _REF:_ is automatically added. The track will be placed outside of RCMASTER signal path and easily auditioned via kbd:[A].

*Hide and Show child tracks / automation lanes* kbd:[E] and kbd:[D]

_Description:_ Hide child tracks to save screen estate and for working with multi-channel takes as if working with just stereo. In _mastering_ mode, the shortcuts also work for hiding and showing automation lanes.

_Notes:_ Select a folder track and press kbd:[E] to hide the children or kbd:[D] to show them. All S-D and razor editing functions work perfectly while folder groups are collapsed. This recreates a popular way of working with classical music takes in Pyramix. In _mastering_ mode, select a track containing automation lanes and press to kbd:[E] hide the automation lanes or kbd:[D] to show them.

*Take Counter Window* kbd:[Ctrl+Enter]

_Description:_ Track take numbers and session name during recording sessions. Schedule recordings by start/end time or duration.

_Notes:_ The window will also open automatically with Classical Take Record (kbd:[F9]) if not already running. It is advised to save your project and name your tracks before starting to record. This ensures that the recorded files have usefully unique names. You can right-click on the window to override automatic take numbering (0 = off (recommended), 1 = override), set a take number to increment from and optionally set a session name to act as media subfolder. You can left-click to recalculate the track count if you have removed some unused files from the project path. The calculated upcoming take number factors in unused files in the project path so as to avoid any file-naming conflicts. You should find this to be an extremely robust take system that rivals Pyramix, Sequoia etc. To schedule a recording or limit by duration, right-click on the take counter window and add the appropriate entry or entries in HH:MM format. After pressing btn:[OK], the take counter window will display information to the right of the take number. If you enter a start or end time earlier or equal to the current time, the function will assume a next day schedule and will annotate the time with an asterisk (*). Likewise, with both a start and end time, if the end time is earlier than or equal to start, it will assume a time 24 hours later. Don't forget to arm your tracks before walking away!

*Classical Take Record* kbd:[F9]

_Description:_ A one-button shortcut for stopping and starting recording of takes.

_Notes:_ To use, select a folder track, position the edit cursor if necessary and press kbd:[F9]. If the parent isn't already record-armed (probably the case before you start your first recording of the session), the function will first simply record-arm the group so you can usefully monitor incoming signal in addition to opening the take counter window. On a subsequent press of kbd:[F9] recording begins. Press again to stop the recording. To immediately start a new take, simply press kbd:[F9] again. To pause and unpause a recording without starting a new take, toggle the pause button in the transport or use the shortcut kbd:[Ctrl+Spacebar]. Note that in a vertical workflow, the next folder has already been selected, record-armed and that the cursor returns to the original position for easy lining up of takes. If you run out of source groups, the function will automatically create a new one.

*Rank Take Higher* kbd:[Ctrl+=]

_Description:_ Rank higher the last recorded item or selected item(s) (and those in the same group)

_Notes:_ During or after recording, you can rank one or more recorded takes. If no item is selected, the last recorded item (along with other items in the same group) are affected. Otherwise, you can select one or more parent items. The ranking system uses a series of colors and a scale system of plusses and minuses (+/-) added as a suffix to the item name up to a maximum of three symbols. This allows for seven different rankings. Positive rankings are 3 intensities of green (good, very good, excellent), negative rankings are yellow, orange, red (below average, poor, unusable), with neutral (no ranking) using the default item color.

*Rank Take Lower* kbd:[Ctrl+-]

_Description:_ Rank lower the last recorded item or selected item(s) (and those in the same group)

_Notes:_ See the notes above.

*Remove Take Ranking* kbd:[Ctrl+0]

_Description:_ Remove any ranking from the last recorded item or selected item(s) (and those in the same group)

_Notes:_ See the notes above.

*Increment Take Number* kbd:[Shift+F9]

_Description:_

_Notes:_

*Add Track To All Groups* kbd:[Shift+T]

_Description:_ Add a new microphone to all folders (or a single folder) mid-recording session.

_Notes:_ The function will prompt for a track name and then a new track will appear at the end of every folder and mixer track set. You could follow up by moving the track using the function below.

*Delete Track From All Groups* kbd:[Ctrl+Shift+Delete]

_Description:_ Delete the selected mixer track and associated child tracks from all groups in the project.

_Notes:_ Available for both horizontal and vertical workflows, simply select a single mixer track and press the shortcut.

*Prepare Takes* kbd:[T]

_Description:_ Intelligently prepares recorded or imported takes for source-destination editing. Coloring scheme is set in ReaClassical Project Preferences kbd:[F5].

_Notes:_ With a single folder group (or individual tracks), the shortcut will auto-color and group takes from left to right. With a vertical workflow consisting of a destination group and multiple source groups, the function will auto-color top to bottom and group folder items left to right. Essentially in either setup, takes are given different colors and all items associated with a take grouped for editing. The function also allows for takes that don't start or end exactly at the same time (this can happen if you receive pre-edited materials). The end result is if you drag one item of a take group, every other item will move in sync. NOTE: The function was designed for use after initial recording or importing of media but as of 24.5.3 should work at any point during editing (for example to import a patch recording). In this case, the destination group items will switch to using alternating colors so that you can easily see where your edits are on the timeline. And, as of 24.8.5, the function uses the _Prepare Takes: Random colors_ value from ReaClassical Project Preferences to use either the new color scheme (default, set to 0) or the old random color method (set to 1). A reminder that the new REAPER native grouping (when set up via Horizontal or Vertical Workflow functions) works for 99% of situations without Prepare Takes but for takes that don't start or end at quite the same point it is a must. Prepare Takes honors any custom colors set via the Colorize function kbd:[K].

*Duplicate Folder (no items)* kbd:[\ ]

_Description:_ Create a duplicate without media items of the highlighted folder.

_Notes:_ Note that in a vertical workflow, Classical Take Record kbd:[F9] automatically creates new folders if needed, this function does not need to be used when recording material. However, if importing pre-recorded takes and you need more source groups to accommodate the material, this is still very useful.

*Colorize* kbd:[K]

_Description:_ Add a identifying custom color to an item and those in the same group.

_Notes:_ Useful for identifying where a S-D edit originated.

*Audition* kbd:[A]

_Description:_ Mouse-driven auditioning of folders or individual tracks.

_Notes:_ Simply hover the mouse over an area of the project and press kbd:[A] to begin auditioning the audio. With kbd:[A], hover over a folder track to hear the complete mix or a single track within a folder for listening to individual instrument or sections. Note that the kbd:[A] function honors any aux or submix track routing. The main function respects soloed or muted `@` aux, # submix and roomtone tracks so you can easily and quickly set up a custom audition mix including a full mix, just the string submix, a single reverb bus and anything else you can imagine!

*Audition With Custom Playback Rate* kbd:[Shift+A]

_Description:_ Mouse-driven auditioning of folders or individual tracks but with a custom playback rate.

_Notes:_ Works in the same fashion as regular ReaClassical auditioning but you can set the custom playback rate via kbd:[F5]. Note that regular auditioning will automatically use the standard playback rate.

*Whole Project View Horizontal* kbd:[` ]

_Description:_ Zoom to show the whole project horizontally.

_Notes:_ Very useful for a birds-eye view of your project so you can navigate to another section. If there are multiple folders, the function collapses them. If fewer than two folders, the function respects the current folder view.

*Whole Project View Vertical* kbd:[Ctrl+`]

_Description:_ Zoom to show the whole project vertically.

_Notes:_ Very useful for a birds-eye view of your project so you can see all vertical take folders. The function respects current child track visibility to allow for a typical editing situation of viewing all of the destination group but only the folder tracks of source groups.

*ReaClassical Project Preferences* kbd:[F5]

_Description:_ Set S-D crossfade length, CD track offset and INDEX0 pre-gap length (CD player countdown into next track), album lead-out time, Prepare Takes colors, S-D Destination Marker Check Range (ms), REF = Overdub Guide, Add S-D Markers at Mouse Hover.

_Notes:_ These values are saved on a per-project basis. While the INDEX0 pre-gap length can be set lower than 1 second in the dialog box, the _Create CD Markers_ function kbd:[Y] will ignore and use a value of 1 second as this is the lowest that makes any sense for displaying the countdown to the next track. Prepare Takes by default uses the new color scheme for items (`Prepare Takes: Random colors` set to 0) which is two shades of blue for horizontal workflows and blues and greens for vertical workflows thereby aligning closely with the colors of the S-D markers. The old coloring method (_Prepare Takes: Random colors_ set to 1) uses random colors per item group. This can help see where edits have come from but because of the randomness may require several iterations until you avoid clashes or eye-sores! The user can change the checking range (distance beyond an item edge/fade or crossfade) when placing destination IN and OUT markers. Setting to 0 would just check if the marker would be placed _inside_ a item fade or crossfade. If the reference track is set as overdub guide, it will be audible during classical take recording and auditioning which is extremely useful for overdub recording of material after the main session such as a symphonic organ part or narration. Finally, you can set kbd:[1],kbd:[2],kbd:[3], and kbd:[4] to add markers at the mouse hover position vs edit cursor. In this mode, you can also enter the fade editor by hovering of the right-hand items of a crossfaded pair and pressing kbd:[F].

*Find Take (based on filename)* kbd:[Enter]

_Description:_ Enter a take number based on the numerical suffixes at the end of filenames and optional session name to quickly jump to that media item.

_Notes:_ If the function can't find a media item with that take number and optional session name, it will let you know and offer to try again with a different number or session name. This will work for any file-naming system that uses numbers before the file extension such as _mvt1_main_pair-T04.wav_ or _beethoven_cello-take_23.flac_. Note that if the imported or recorded files have zero-padding that is not a problem as the function strips these away. The session name search can be used to find any text in the filename and allows for partial searches. If you have used an item to create an S-D edit, searching for a take will ignore these items and move directly to the original sources.

*Jump To Time (Selected Item(s) or Project)* kbd:[Tab]

_Description:_ Press kbd:[TAB] to jump to a specific absolute or relative time using right-aligned logic, similar to video editing applications. This can be an absolute time within the project or an relative position inside a selected item or a set of consecutive crossfaded items.

_Notes:_ Various use-cases include 1) a musician or producer giving you an exact time in draft exported audio of a heavily-edited symphony movement where they identified extraneous noise or a noticeable edit, 2) building S-D edits from a list or score which includes take number and timecode. Prefix with + or - to make relative jumps.

*Source-Destination Markers* kbd:[1], kbd:[2], kbd:[3], kbd:[4]

_Description:_ Add source-destination markers ready for making the edit.

_Notes:_ kbd:[1], kbd:[2] = destination IN/OUT; kbd:[3], kbd:[4] = Source IN/OUT. In between the destination markers is where the edit will actually happen. In between the source markers is where the material is taken from. Use all four markers for 4-point editing. Use any combination of 3 markers for 3-point editing. Use either 1 source and 1 destination (more useful) or just the source markers for 2-point editing (less useful). By default, the markers are added at the edit cursor location. It is very important and useful to note is that the source marker labels reflect which source group was highlighted when the markers were placed. In other words, to create source markers at the edit cursor, first select the item in the chosen folder track and then use the kbd:[3] & kbd:[4] shortcuts. This means that when the actual edit is made (using kbd:[5]) it doesn't matter what is highlighted at the time. Obviously this is only useful if using a vertical take system approach. Additionally, you can set the placement of S-D markers at mouse hover position via ReaClassical Preferences (kbd:[F5]). The benefit, other than speed, is that you don't have to worry about making sure source tracks are selected by clicking on the item - simply hover over the desired item and add the source markers!

If you attempt to set one of the destination markers inside of an existing crossfade or within 500ms of a crossfade or item edge, the function will alert you (pressing btn:[OK] places the marker anyway). This helps avoid awkward _sliver_ edits that can happen especially if you are zoomed out and placing markers by ear. You can set the check range via kbd:[F5]. The check range (in milliseconds) is the distance beyond an item edge, fade or crossfade. For example, setting to 0 would only check for placement _inside_ a fade or crossfade.

*S-D Edit* kbd:[5]

_Description:_ Make the source-destination edit (2-, 3- and 4-point editing)

_Notes:_ Once you have placed your S-D markers press kbd:[5] to make the edit. Whatever the number of markers you used, the edit will be crossfaded using a short equal power fade (you can change this in REAPER via menu:Preferences...[Media Item Defaults]) and when using 4 markers, the S-D markers removed ready for the next edit. The edits are perfectly crossfaded and the user only needs to focus on the selection of source material. For any S-D edit you can, of course, undo the action and return to the previous state. The desired crossfade length is set via ReaClassical Project Preferences kbd:[F5]. Note that this function can be used in multi-tab S-D editing mode (see below).

*Reverse S-D Edit* kbd:[6]

_Description:_ Make a _reverse_ source-destination edit (3-point edit)

_Notes:_ Place your destination markers using kbd:[1] and kbd:[2], then set a source IN marker with kbd:[3]. Pressing kbd:[6] will copy or move the material between the destination IN and OUT markers to the selected source group, as determined by the kbd:[3] shortcut. Upon execution, you will be prompted to choose whether to copy or move the material. This function operates similarly to the *Copy/Move Destination Material to Source* functions but allows for precise selection using S-D markers.

*3-point _Assembly Line_ Edit* kbd:[F3]

_Description:_ Uses both source markers and destination-IN marker to compile edits from start to finish.

_Notes:_ The destination-IN marker is retained and placed at the end of the edit so that for subsequent operations the user only has to set the source markers. Worth repeating from the S-D edit notes:

____ _…the source marker labels reflect which source group was highlighted when the markers were placed. In other words, to create source markers, first select the item in the chosen folder track and then use the kbd:[3] & kbd:[4] shortcuts. This means that when the actual edit is made (using kbd:[5]) it doesn't matter what is highlighted at the time._ ____

If you accidentally move the location of the destination IN marker in the middle of assembly line editing, the function will let you know and offer to move the marker back to the right edge of the latest item in the edit. This will even allow you to do some regular 3- or 4-point editing earlier in the sequence before continuing with the assembly line edits. Just place the destination IN marker anywhere in the project and answer btn:[No] when the message box appears. Note that this function can also be used in multi-tab S-D editing mode (see below).

*Insert with* *Timestretching* kbd:[F4]

_Description:_ Makes the source material fit the the space in between the destination markers using time-stretching vs rippling later material.

_Notes:_ Requires placing all four S-D markers. This is less useful for classical music editing but perhaps very useful for video work where replacement material has to fit exactly into the time used by the original. Crossfade length is set via ReaClassical Project Preferences kbd:[F5]. Note that this function can also be used in multi-tab S-D editing mode (see below).

*Delete with Ripple* kbd:[Backspace]

_Description:_ Deletes material between the source markers, rippling all later material.

_Notes:_ This only affects the folder group that was highlighted when the source markers were placed which will almost always be the destination group (the top folder in the project). Crossfade length is set via ReaClassical Project Preferences kbd:[F5].

*Delete Leaving Silence* kbd:[Ctrl+Backspace]

_Description:_ Deletes material between the source markers, no rippling of later material.

_Notes:_ This is similar to _Delete with Ripple_ but instead leaves a gap where the original source material existed.

*Copy/Move Destination Material to Source*

_Description:_ Copies or movies the entire destination material from the destination group to a newly-created source group below.

_Notes:_ Run either the copy or move version of the function from the ReaClassical toolbar (no need to ensure the first track is selected) and the function will copy or move all items and edits from the destination group directly below to a newly created source group with Eastern Blue color for identification purposes. This allows for saving versions of finished edits either via iteration (_copying_ so you can continue to make further edits) or fresh (_moving_ so you can compile an alternate version of a best take from scratch). These different edits can then be easily auditioned via the kbd:[A] shortcut. This is similar to a Pyramix-style iterative editing method while still maintaining the destination group as the uppermost group.

*Add Source Project Marker* kbd:[Ctrl+Alt+3] or kbd:[Ctrl+Alt+4]

_Description:_ Enables multi-tab editing

_Notes:_ To work in multi-tab S-D edit mode, the user is required to use the S-D project markers as a pair, one in the _destination_ tab and the other in the _source_ tab. In multi-tab S-D edit mode, any source makers placed by the user are not deleted in order to aid a quick undo in the destination tab ready to reapply a tweaked edit.

*Add Destination Project Marker* kbd:[Ctrl+Alt+1] or kbd:[Ctrl+Alt+2]

_Description:_ Enables multi-tab editing

_Notes:_ To work in multi-tab S-D edit mode, the user is required to use the S-D project markers as a pair, one in the _destination_ tab and the other in the _source_ tab. In multi-tab S-D edit mode, any source makers placed by the user are not deleted in order to aid a quick undo in the destination tab ready to reapply a tweaked edit.

*Delete all S-D Markers* kbd:[Ctrl+Delete]

_Description:_ Deletes source and destination markers.

_Notes:_ Useful if you want to abandon a S-D edit, however, there's also no problem leaving the markers for another time given that shortcuts kbd:[1], kbd:[2], kbd:[3] and kbd:[4] replace any existing version of the marker. Also when running _Create CD Markers_ function all markers are deleted in any case.

*Delete all S-D Project Markers* kbd:[Shift+Delete]

_Description:_ Deletes both source and destination project markers

_Notes:_ In order to switch back to regular single-tab S-D editing, it is important to run this command otherwise the S-D edit functions will continue to attempt to find markers elsewhere.

*Classical Crossfade Editor* kbd:[F]

_Description:_ Opens a custom two-line crossfade editor view for precise finessing of S-D edits.

_Notes:_ To enter the crossfade view, select the right-hand item of a crossfaded item pair (or hover over the item if _Add S-D Markers at Mouse Hover_ is set to 1 in ReaClassical Project Preferences kbd:[F5]). The user is then presented with a zoomed-in view of the edit. Red is always the left item, green the right. For safety reasons, all items in the first folder before the left red item are locked to avoid inadvertently messing with an existing fade. Further, ReaClassical uses a feature similar to _Classical Mode_ in Sequoia's fade editor. Essentially, the user is free to move the left item but on running Classical Crossfade kbd:[X] or exiting using kbd:[F](after, for example, setting a more complex fade by hand), the red item snaps back to its original position (all future items are also relatively shifted), thereby perfectly preserving the previous fade. To immediately audition, use the A shortcut in one of four areas. Hover the mouse in either of the blank areas (no media item) in the top left or bottom right of the view to audition the function from that location to the mirrored location on the other side of the edit. Note how easy it is to quickly set an audition length! Or, hover the mouse on the first item and press kbd:[A] to just audition the material into the fade. Hover and press kbd:[A] on the outgoing item to only hear the material out of the fade. Note that auditioning in the arrange window or in fade editor mode maintains muted items on the folder track.

To actually finesse the edit, ensure at least one of the crossfaded items is selected. Then hover your mouse in a blank area (similar to the above fade editor audition tool process) and press kbd:[Z]. You'll notice that the waves mirror extend to the mouse position to allow for easy lining up of the material. Place the edit cursor at an appropriate edit point on the left red item (i.e. just before a transient) then simply move the right green item to align and then press kbd:[X]. Audition again, kbd:[Z] to expand again. You can quickly move to the previous or next crossfade pair (with all coloring and locking automatically happening behind the scenes) by pressing kbd:[Q] or kbd:[W]. Or, simply press kbd:[F] to exit the fade view (it goes without saying that the original colors of the project items are restored).

Note also that while in crossfade editor view, any edits only affect the destination group.

*Edit Classical Crossfade* kbd:[Z]

_Description:_ Expand the crossfade for editing while in the crossfade editor view.

_Notes:_ This shortcut will only work while in crossfade editor view. If you attempt to use it in other situations, you will receive a helpful message. As described above, when either one or both items are highlighted, hover your mouse in a blank area and press kbd:[Z]. You'll notice that the waveforms are mirror extended to allow for easy lining up of the material. Simply put the edit cursor just before a transient on the red item, move the green right item to align, and then press kbd:[X].

*Classical Crossfade* kbd:[X]

_Description:_ Create a _classical_ crossfade either in regular project view or crossfade editor mode.

_Notes:_ While in the project view, drag an item (or grouped items) over another, move the edit cursor where you want the edit to happen and press kbd:[X]. Given the availability of S-D edit functionality and group razor-editing, this function is less useful in this context. However, it is essential in the crossfade editor mode for making the edit. Crossfade length is set via ReaClassical Project Preferences kbd:[F5].

*Build Edit List*

_Description:_ Creates an edit list for use by video editors.

_Notes:_ Choose the _BWF Start Offset_ version when the audio and video was synchronized to a timeclock and _using source file timing_ to use internal times of the audio sources. Export CSV data using the button below the table. Use the offset option to apply a constant value in frames to correct possible timeclock sync issues.

*Mastering Mode* kbd:[Ctrl+M]

_Description:_ Allows for focused work on the destination group. Couple with _automation_ mode, to add mixer and FX parameter values as envelope points

_Notes:_ Enter _automation_ mode via kbd:[Ctrl+I]. All the envelope buttons will turn blue (_latched preview_) and you will see a message box with instructions. You can then use the function below. Exit _automation_ mode again via kbd:[Ctrl+I]. The envelope buttons will then turn green (_read_ mode).

*Automation Mode* kbd:[Ctrl+I]

_Description:_ Coupled with _mastering_ mode, allows for adding mixer and FX parameter values as envelope points

_Notes:_ Enter _automation_ mode via kbd:[Ctrl+I]. All the envelope buttons will turn blue (_latched preview_) and you will see a message box with instructions. You can then use the function below. Exit _automation_ mode again via kbd:[Ctrl+I]. The envelope buttons will then turn green (_read_ mode).

*Insert Automation* kbd:[I]

_Description:_ Insert mixer and FX values as envelope points into automation lanes

_Notes:_ Simply set any desired mixer controls or parameters in an open FX window) on one or more tracks and press kbd:[I] to enter the values as points on the automation lanes at the edit cursor position or, if one exists, within the time selection.

*Reposition CD Tracks* kbd:[Ctrl+Y]

_Description:_ Create uniform custom spacing between CD tracks.

_Notes:_ Using the same system as _Create CD Markers_ below, this function works intelligently based on whether items have a take name. If the take name is present, the desired silent gap is created. If not, the crossfade (or gap) is respected by shifting the item by the same amount as the previous one.

*Shift CD track one track to the left/right* kbd:[Ctrl+{cursorleft}] and kbd:[Ctrl+{cursorright}]

_Description:_ Shift CD tracks left and right along the timeline.

_Notes:_ Select the start of a CD track and use the shortcuts to rearrange the order of your album. The function treats crossfaded CD track starts as part of the same group to cover instances where a movement follows on _attacca_ to maintain the correct order. Then simply run or re-run the _Create CD Markers_ function to create new markers that align with item starts.

*Remove Take Names from Destination Parent* kbd:[Ctrl+T]

_Description:_ Run after source-destination editing is complete to remove recorded/imported take names from destination parent items in preparation for using the Create CD Markers function.

_Notes:_ As mentioned below, add take names only to destination parent items that are to become CD track starts.

*Create CD Markers* kbd:[Y]

_Description:_ Auto-generation of CD/DDP markers, UPC/ISRC codes, CUE file, metadata report, album reports, and room tone automation, for efficient DDP, bin/cue and individual file exporting. Checks against Redbook standards and returns warning messages if there are 1) more than 99 tracks, or 2) There are tracks shorter than 4 seconds, or 3) the total length of the project is greater than 79.57 minutes.

_Notes:_ If working in horizontal workflow, ensure that there is over a minute's worth of empty timeline between the end of the proposed album and any other source material. Instead, you can also choose to drag any source material to new group by first creating an empty duplicate folder via kbd:[\ ].

This might be the biggest time-saving function in the ReaClassical system. It works as follows: 1) Edit gaps between items until you are happy 2) Add take names (and optionally other metadata) only to items that will become CD track starts 4) Add a take name starting with @ to the final item of the album and optionally add album-wide metadata 4) Run the function via shortcut kbd:[Y] and you will be asked to enter UPC/ISRC (optional). Done! Note that ISRC codes are auto-generated per track based on the numbers you enter.

You can add audio to the initial pre-gap (easter egg track) by not giving the first item (or crossfaded items) a take name. The function will assume that this is supposed to be hidden and generate the initial pre-gap length accordingly. All album metadata is placed towards the end of the album inside a default 7-second silent lead-out (so that CD players in cars don't immediately cycle back to the first track without a little breathing room). This value can be changed via the ReaClassical Project Preferences kbd:[F5]. In addition to markers, regions are also generated for easy exporting of individual tracks. If you need a countdown into a track, simply add a ! at the start of the take name (e.g. _!Allegro_). Then after running the function adjust the position as desired (it defaults to 3 seconds in length but this can easily be set in ReaClassical Project Preferences). It is worth repeating at this point that you should only give names to items that are track starts. If you skip an item, the function rightly assumes it is part of the previous track. Note that the markers snap to exact CD frames and if the media item start is in between CD frames, the function will always place the marker on the earlier of the two. By default, the function uses a 200ms offset for placement of the markers (as in, markers appear 200ms to the left of the media item start) but, again, this value can be set via ReaClassical Project Preferences.

If a room tone track exists in the project, the function will also generate volume automation to create perfect crossfades with the items on the first destination track. Slicing and dicing room tone audio to fill in digital silence is now a thing of the past. Simply add a long recorded or convolution-generated room tone audio item before running the function. The ReaClassical way of dealing with room tone is non-destructive and instant!

In addition, the function automatically generates a CUE file and album reports in both HTML and plain text formats. The year and audio format used by the CUE can be set via ReaClassical Project Preferences kbd:[F5].

I feel that once you try this CD/DDP marker generation workflow, it is difficult to ever go back to other ways of working. The key thing to think about is that the markers and room tone fade-ins and outs are trivially easy to recreate if you change a gap between items or even rearrange the order of tracks. Just run the function again. The key is the workflow: all marker generation is automatically based on item positioning and naming. Plus, all metadata and ISRC is saved into the project file so once entered you don't have to ever type it in again unless you need to make changes. Room tone volume changes are made via auto-generated volume envelope points that precisely map REAPER's built-in fade curves.

Hopefully you agree that this way of working with CD/DDP layout is a game-changer, a real time-saver and simply a better way of thinking about this portion of the mastering process. For more information about DDP metadata see https://raw.githubusercontent.com/chmaha/ReaClassical/refs/heads/main/docs/manual/src/assets/ddp_info.txt[here] (also available via the Render dialog via menu:Format[DDP] and clicking on btn:[Help]).

*Show Metadata Report*

_Description:_ Runs automatically as part of Create CD Markers function or separately via menu:ReaClassical[Mastering > Show Metadata Report]. The function shows all proposed metadata that will end up as part of the rendered DDP fileset.

_Notes:_ The function will alert the user if some track metadata labels (COMPOSER=, PEFORMER=, SONGWRITER=, ARRANGER=) have been used without also using them album-wide via the `@` item name.

*Show Statistics* kbd:[F1]

_Description:_ For a complete set of statistics on the ReaClassical project, either for your own information or to assist with billing a client, use the shortcut or navigate to menu:ReaClassical[Utilities > Show Statistics].

_Notes:_ For determining project age, the project needs to have been created in ReaClassical 25.3 or higher. Otherwise, it will display _n/a_.

*Lock Toggle (deprecated)*

_Description:_ Lock every source group (leaving the destination group free for editing in ripple-all mode)

_Notes:_ This function is now deprecated but I will leave in place for now. It was useful before the new _Create CD Markers_ function came into being as a way to engage ripple-all mode without disturbing source group items, thereby allowing moving of destination material along with CD markers in the final stages of the mastering process. There is no doubt that I much prefer working with the newer function. The lock toggle icon on the custom toolbar has now been replaced by a mug to represent the _Create CD Markers_ action.