@description Eurydice Console
@author chmaha
@version 1.0
@changelog
  Initial Commit
@metapackage
@provides
  Eurydice_Bus.jsfx
  Eurydice_Channel.jsfx
  [rpp] ReaClassical_Eurydice.RPP
  
@about
  These jsfx digital console emulation plugins use DSP from airwindows PurestConsole2.
  Also included is the Eurydice project template with plugins already in place (requires ELSA and RCGain to be installed)
