== Preliminaries

It is important to note that if you already own REAPER then the world of classical editing including source-destination editing (aka 2-, 3-, and-4-point editing) is available at no extra cost to you via the freely available ReaClassical Core package. There's no need to spend any of your hard-earned money on Sequoia, Pyramix or SaDiE in order to make editing precise and efficient. As a classical engineer myself, I can say with certainty that what I am about to share with you covers all my editing needs. Indeed, I couldn't return to the old way of working at this point. Your mileage may vary and I'd love to hear from you if there are functions that you feel might be missing. 

=== ReaClassical vs ReaClassical Core

ReaClassical Core serves as an accessible entry point to the complete recording, editing, mixing, and mastering world of ReaClassical. It's a great way to get started editing the _ReaClassical_ way inside of a regular REAPER instance. If you like _Core_, consider trying the full ReaClassical ecosystem - it's also completely free and open source! For more information see https://reaclassical.org.

=== Compatibility

ReaClassical Core runs on any system that is compatible with REAPER (nine architectures!). This includes 64-bit and 32-bit versions of Windows, MacOS and Linux (including Raspberry Pi).

=== This Manual

This online manual, located at https://reaclassical.org/core, serves as the official documentation for ReaClassical Core. The structure of the manual is designed to take the user through preliminary remarks, then a detailed look at editing workflows. After some brief closing remarks, there follows the appendices (descriptions of all the ReaClassical Core functions and recommended keyboard shortcuts). I highly recommend doing a complete read of the short manual and becoming very familiar with the appendices.

This manual is released under the GNU Free Documentation License v1.3. See https://www.gnu.org/licenses/fdl-1.3-standalone.html.

=== REAPER Community

The https://forum.cockos.com/showthread.php?t=265145[community thread] plays an important role in the development of ReaClassical. Not only is it a place for users to suggest feature requests and point out bugs but also discuss more general classical music recording, mixing and mastering techniques. It also serves as something of a development blog as I not only announce the regular releases but also document the under-the-surface details for those that are interested.

Relatively new is the https://discord.gg/Gu2m9ccHGS[ReaClassical Discord server]. This is a great place for live support, general chat, proposing feature requests, workflow discussion, and letting the community know about albums or individual pieces you have created with the help of ReaClassical or ReaClassical Core.

=== Ways to Contribute

The most important way users can contribute to the development of ReaClassical or ReaClassical Core is to actually use the tools! It makes me happy to know that engineers can make whole professional-sounding and technically accurate masters from ReaClassical. Another is to suggest features or let me know about bugs. You can either do this on the https://forum.cockos.com/showthread.php?t=265145[thread] or via the https://github.com/chmaha/ReaClassical/issues[Issues] page on the ReaClassical GitHub. Finally, I'd be glad of any monetary donations. You can use https://www.paypal.com/donate/?hosted_button_id=DHA5C96L6W8VN[PayPal] to do so. 

=== Spread the Word!

If you've enjoyed using ReaClassical Core in your projects, I'd be incredibly grateful if you could mention it in your album booklets, social media video descriptions, or anywhere you typically include session details. A simple acknowledgment alongside your usual credits helps spread the word and supports the continued development of the tool.

=== Buy ReaClassical Merch

Get print-on-demand ReaClassical merch like shirts, mugs, totes, pins, stickers and more through my https://www.teepublic.com/user/reaclassical[TeePublic store]!

=== Source Code

The source code for ReaClassical and ReaClassical Core, the mastering grade ReaClassical plugins, this manual and the website can all be found https://github.com/chmaha/ReaClassical[here]. ReaClassical and ReaClassical Core are https://www.gnu.org/licenses/gpl-3.0.html[GPL-3.0] licensed.

=== Development Style

Due to working on GitHub and releasing the functions via ReaPack, I have the ability to push bugfixes and new features very quickly into an existing ReaClassical install. Often bugfixes happen within minutes or hours of receiving the report. When I dream up new features, the development often happens in rapid fashion over the course of a few days. However, now that ReaClassical has what I consider a mature feature set, I foresee maintenance and occasional bugfixes becoming more central to the process. This will give me more opportunity to work on this documentation, a complete video tutorial series etc. Part of development is also ensuring that ReaClassical continues to operate as expected with the latest REAPER versions. That's not to say there won't be new features appearing! As the REAPER developers add more new features, I will always check to see what might be useful for ReaClassical. 

=== Versioning

Unlike the full ReaClassical system, ReaClassical Core will not receive as many updates as the full ReaClassical system and these will be mostly limited to bugfixes where necessary, and ensuring that the functions continue to work as expected in future REAPER versions. Therefore, a simpler MAJOR.MINOR versioning has been selected.

=== Tools and Languages

ReaClassical Core works on top of https://www.reaper.fm/[REAPER], the digital audio workstation and utilizes https://reapack.com/[ReaPack] and https://www.sws-extension.org/index.php[SWS Extensions]. ReaClassical Core functions are coded using https://www.lua.org/[Lua]. All coding is done either in REAPER's ReaScript Development Environment, https://code.visualstudio.com/[vscode] or https://apps.kde.org/kate/[kate] on Linux. The online manual is written in https://asciidoc.org/[AsciiDoc]. The ReaClassical Core logo and banner were created in https://www.gimp.org/[GIMP].

=== Changelog

The changelog for ReaClassical Core functions can be found by double-clicking on the ReaClassical Core package in ReaPack and navigating to the `History` tab. Whenever you sync ReaPack via menu:Extensions[ReaPack > Synchronize packages], this information should also appear automatically.
