=== Converting an existing REAPER project

ReaClassical has gained the ability to import any REAPER project with the ReaClassical_Convert REAPER project function (also available in the top ReaClassical menu via menu:Project Setup[Convert REAPER Project]). It was primarily intended to import simple ReaClassical Core editing projects (an entry point into ReaClassical-style S-D editing using a regular REAPER instance). However, because of the dizzying amount of custom routing and folder hierachy that is indeed possible inside a REAPER project, the following happens during conversion:

. A new project tab is created and `_converted` suffix added to the RPP file
. Any folders are flattened
. Any empty tracks are deleted
. A single folder is formed in preparation for a horizontal workflow
. Any effects are moved to the relevant mixer tracks
. Any custom routing is removed

At this point, a familiar horizontal workflow is set up and takes prepared automatically. All that is left for the engineer to do is recreate any custom routing using ReaClassical special tracks (kbd:[#]) and copy/paste any previous bus effects that would have been deleted due to being an empty track. For example, if the original REAPER project used folders to organize orchestral section microphone channels, this would be recreated by adding a `-` suffix to the relevant regular tracks then pressing `F7` (thereby removing a direct connection to RCMASTER) and routing them to one or more submixes.