=== Mixing

==== FX Plugins

ReaClassical is shipped with various mastering-grade JSFX plugins to cover typical needs although obviously REAPER allows for any 3rd party plugins. For a list of recommended free plugins see Appendix C. In ReaClassical, you should add plugins to the dedicated mixer tracks.

==== Aux & Submix

Users have the ability to create aux and/or submix tracks that stay visible (and stay after the mixer tracks). To set up, simply create a single folder via Horizontal Workflow kbd:[F7] and/or Vertical Workflow kbd:[F8] then create as many aux/submix tracks after the mixer tracks as you like via kbd:[# ]. It is important to keep the `@` or `\#` at the beginning of the track but you can add any name you'd like e.g. _@hall-verb_, _#strings_. To route, click-drag from a mixer track's routing stripes to the desired `@` or `#` track. When using any of the ReaClassical functions such as auditioning, these tracks will remain visible.

For # submix tracks, simply add a hyphen (-) at the end of desired track names in the mixer tracks and sync via kbd:[F7] or kbd:[F8]. Now those related mixer tracks will not route directly to RCMASTER. As an example, say mixer tracks 3-6 are all string section microphones and you'd like to sum them all to a string submix track called _#strings_. Just add a hyphen to the end of the names for mixer tracks 3-6, sync and then create the routing to #strings via click-dragging from the routing stripes. This routing is maintained during kbd:[F7] or kbd:[F8] syncs.

==== Roomtone

In a live concert recording that contains audience noise in between movements and applause at the end of a complete piece, it is often desirable to give the impression of a clean recording with no audience present. Recorded or generated room tone then becomes very important as an alternative to audio fading to complete digital silence which destroys the illusion of listening back to a live concert. ReaClassical includes a dedicated room tone track for this purpose. This way, the auditioning tool will keep the track displayed in both track and mixer panels. Add via kbd:[#]. Once added, you can add clean recorded noise captured before or after the concert or generate endless roomtone the length of your project from a very small portion of clean silence from the concert itself (hint: try using a white noise generator into a convolver such as ReaVerb that uses a few seconds of clean room tone as the impulse! See Appendix D for the method…). As of ReaClassical 24.12, the Create CD Markers function automatically generates precise volume automation at the track level to seamlessly fade in and out of room tone! See the mastering section for more details. Please not that there is a limit of one reference track per project.

==== Reference Track

Add a reference track via kbd:[#] to allow for importing a commercial album track or similar to help achieve the desired loudness levels, EQing etc for your own material. The reference track is deliberately placed outside of the RCMASTER structure and can therefore be quickly auditioned independent of any effects you have on the mixer and RCMASTER tracks.


==== Maintaining/Breaking Connections to RCMASTER

When adding special tracks via kbd:[#], set Maintain Mixer => RCMASTER to 0 to add a hyphen (-) to the end of every mixer (`M:`) track thereby removing the direct connection to RCMASTER allowing for all sorts of custom routing via submixes etc. By default, the final option is always set to 1 to maintain the current routing.
