=== System Tweaks

==== Windows

For a modern Windows 10/11 setup, required tweaks are minimal. Ensure that you are using 'High Performance' or ideally 'Ultimate Performance'. which, if not available, can be activated by opening a command prompt and pasting:

----
 powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61
----
You can then select it from the usual power plan dialog. For best device performance, remember to use the ASIO drivers that were included with your audio interface. Consider disabling your network card during mission-critical recording. For further tips see Microsoft's https://devblogs.microsoft.com/windows-music-dev/unofficial-windows-10-audio-workstation-build-and-tweak-guide-part-2/[Unofficial Windows 10 and 11 Audio Workstation build and tweak guide]. Of particular interest is Part 3 which discusses what _not_ to do (including not setting your processor scheduling to 'background services').

==== MacOS

Performance should be excellent out of the box. Remember to disable energy saving (menu:System Preferences[Energy Saver]) so that sessions are not interrupted. Consider disabling your network card during mission-critical recording. If you are experiencing any audio issues while in your DAW, for tips see Focusrite's https://support.focusrite.com/hc/en-gb/sections/360004958539-Optimisation[optimization page].

==== GNU/Linux

Linux users should visit my https://github.com/chmaha/ArchProAudio[Arch Pro Audio Guide]. Performance out of the box on Linux is getting better with every kernel release and is on par or better than Windows. As a starting point, ensure that your username is set up for realtime privileges (step 3) and that you set several kernel parameters to ensure you are running the performance governor, threadirqs and dynamic preempt (step 4). To make things even easier, consider using a dedicated audio/video distro like https://www.bandshed.net/avlinux/[AVLinux] or https://ubuntustudio.org/[Ubuntu Studio] where everything is already set up for you.

==== Cross-platform

The good news is that REAPER and ReaClassical run on nine different architectures. You should always be able to open up a project on another machine even if it is running a different OS. Plus, ReaClassical includes various mastering-grade plugins in JSFX format that run on all architectures.