=== Converting a Standard REAPER Project

ReaClassical has the ability to import any REAPER project (available in the top ReaClassical menu via menu:Project Setup[Convert REAPER Project]). Because of the dizzying amount of custom routing and folder hierachy that is possible inside a standard REAPER project, the following occurs during conversion:

. A new project tab is created and `_converted` suffix added to the RPP file
. Any folders are flattened
. Any empty tracks are deleted
. A single folder is formed in preparation for a horizontal workflow
. Any effects are moved to the relevant mixer tracks
. Any custom routing is removed

At this point, a horizontal workflow is set up and all that is left for the engineer to do is recreate any custom routing using Mission Control. For example, if the original REAPER project used folders to organize orchestral section microphone channels, this would be recreated by clicking on the appropriate routing buttons to disconnect from RCMaster and instead route to one or more newly-created submix tracks.