=== Install

==== Easy Complete Portable Installation (official method)

. Follow the installation instructions https://github.com/chmaha/ReaClassical/blob/v25/install_instructions.md[here] or in the _Installation & Update_ section of the https://reaclassical.org/quick_start_guide.html[Quick Start Guide]. Simply run where you would like the ReaClassical folder to be created.
. Start REAPER/ReaClassical.
. Follow the update instructions on the following page to get the latest and greatest versions of the ReaClassical functions, toolbar and keymap.

Note that if the ReaClassical folder already exists, the installer will automatically add a unique suffix to ensure nothing is overwritten.

==== Just The S-D Editing Scripts and Plugins?

Install both ReaPack and latest SWS Extensions if you haven't already. Import my index.xml into ReaPack (see the ReaPack user guide if you are unsure how) and search for `ReaClassical Core` for the S-D editing metapackage and `RCPlugs` for the classical jsfx plugins. Note that out of the box this does not give you the full benefits of ReaClassical which include keyboard shortcuts, custom toolbar etc. However, it's an easy way to start if you are already familiar with ReaPack and SWS and want to check out source-destination editing in your existing REAPER install. Note that you do need SWS installed for the functions to work as expected.

Important: If you enjoy ReaClassical Core and want to move to a full ReaClassical experience, please use the https://github.com/chmaha/ReaClassical/blob/v25/install_instructions.md[portable install instructions]. It is the only approved installation method.