@description RCPlugs
@author chmaha
@version 1.9
@changelog
  Add Mid-Side encoder-decoder
@metapackage
@provides
  RCComp.jsfx
  RCDeEss.jsfx
  RCDeEss_Advanced.jsfx
  RCDither.jsfx
  RCChannelEQ.jsfx
  RCGain.jsfx
  RCLimiter.jsfx
  RCParallelK.jsfx
  RCMasteringEQ.jsfx
  RCInflator.jsfx
  RCTimePhase.jsfx
  RCConsoleBus.jsfx
  RCConsoleChannel.jsfx
  RCConsoleFinalizer.jsfx
  RCMidSide.jsfx
@about
  These plugins are suitable for classical music mixing and mastering.
