@description ReaClassical Essentials
@author chmaha
@version 1.0
@changelog
  Initial metapackage release
@metapackage
@provides
   RCComp.jsfx
   RCDeEss.jsfx
   RCDither.jsfx
   RCEQ.jsfx
   RCGain.jsfx
   RCLimiter.jsfx
   RCParallelK.jsfx
@about
  These essential jsfx plugins provide everything you need for classical music mixing and mastering.
  Compressor, Parallel Compressor, EQ, Limiter, DeEsser, Gain and Dither.
