@description ReaClassical Essential Plugins
@author chmaha
@version 1.2
@changelog
  Add RCDeEss Advanced
@metapackage
@provides
   RCComp.jsfx
   RCDeEss.jsfx
   RCDither.jsfx
   RCEQ.jsfx
   RCGain.jsfx
   RCLimiter.jsfx
   RCParallelK.jsfx
   RCDeEss_Advanced.jsfx
@about
  These essential jsfx plugins provide everything you need for classical music mixing and mastering.
  Compressor, Parallel Compressor, EQ, True Peak Limiter, DeEsser, Gain and the world's best Dither.
