== Installing ReaClassical Core

Requirements: _ReaPack_, _SWS/S&M extension_

To install ReaClassical Core:

. Download ReaPack from https://reapack.com/. Read the instructions at https://reapack.com/user-guide for how to install the plugin, add repositories, add packages etc.
. Import my repository into ReaPack by copying and pasting this https://github.com/chmaha/ReaClassical/raw/main/index.xml[link] into ReaPack. 
. Search for "SWS" and mark "SWS/S&M extension" for install.
. Search for "core" in the ReaPack and mark "ReaClassical Core" for install. 
. Click "Apply".

== Assigning Keyboard Shortcuts

Unlike the full ReaClassical ecosystem, ReaClassical Core does not provide any keyboard shortcuts and leaves it up to the user to assign as they see fit. The appendix includes suggested shortcuts. Open up the actions menu via keyboard shortcut kbd:[?] or by navigating to menu:Actions[Show action list...] to see the ReaClassical Core functions (you can filter at the top of the screen). You can add your own shortcuts via the box in the bottom left of the actions menu dialog. For reference (from REAPER's own user guide), here is a table of equivalent modifier keys for the different OSes:

[.center, width="75%",cols="^,^"]
.Shortcut Equivalents
|===
|*PC (Windows or Linux) Key*|*Mac (MacOS) Key Equivalent*
|Shift|Shift
|Control (Ctrl)|Command (Cmd)
|Alt|Option
|Windows|Control
|===
