@description ReaClassical Miscellaneous Plugins
@author chmaha
@version 1.2
@changelog
  Add Discordia
@metapackage
@provides
   Amphitrite.jsfx
   Aurora.jsfx
   Eris.jsfx
   flattop.jsfx
   Lyra.jsfx
   Magnetique.jsfx
   MuTube.jsfx
   port-and-lemon.jsfx
   Sillons.jsfx
   Titan.jsfx
   Discordia.jsfx
@about
  Various other jsfx plugins including compressors, gate, saturation/distortion, clipper, Vinyl and Tape emulations...
