@description ReaClassical Dither Plugins
@author chmaha
@version 1.4
@changelog
  Add WTF Wide to WTFDither
@metapackage
@provides
   Nintenda.jsfx
   six-dither_sid.jsfx
   Stan.jsfx
   Twilight.jsfx
   WTFDither.jsfx
   Xonnos Dither.jsfx
   ReelDither.jsfx
   GroovyDither.jsfx
@about
  These jsfx Dithers plugins provide for every sort of Dither you could ever need.
  Includes TPDF, single-pole high-pass, and various other boutique wordlength reducers from airwindows.
