@description ReaClassical Dithers
@author chmaha
@version 1.1
@changelog
  Change reapack headers
@metapackage
@provides
   Nintenda.jsfx
   six-dither_sid.jsfx
   Stan.jsfx
   Twilight.jsfx
   WTFDither.jsfx
   Xonnos Dither.jsfx
@about
  These jsfx Dithers plugins provide for every sort of Dither you could ever need.
  Includes TPDF, single-pole high-pass, and various other boutique wordlength reducers from airwindows.
